/** Nomes dos canais IPC. Usados em tempo de execução pelo main e pelo preload. */
export const CANAIS = {
  sessao: {
    obter: 'sessao:obter',
    entrar: 'sessao:entrar',
    sair: 'sessao:sair',
    presenca: 'sessao:presenca',
    primeiroAcesso: 'sessao:primeiro-acesso',
  },
  usuarios: {
    listar: 'usuarios:listar',
    listarOnline: 'usuarios:listar-online',
    criar: 'usuarios:criar',
    atualizar: 'usuarios:atualizar',
    alterarSenha: 'usuarios:alterar-senha',
    excluir: 'usuarios:excluir',
  },
  responsaveis: {
    listar: 'responsaveis:listar',
    criar: 'responsaveis:criar',
    atualizar: 'responsaveis:atualizar',
    excluir: 'responsaveis:excluir',
  },
  cronogramas: {
    listar: 'cronogramas:listar',
    obter: 'cronogramas:obter',
    criar: 'cronogramas:criar',
    atualizar: 'cronogramas:atualizar',
    excluir: 'cronogramas:excluir',
  },
  tarefas: {
    obterEstrutura: 'tarefas:obter-estrutura',
    criar: 'tarefas:criar',
    atualizar: 'tarefas:atualizar',
    excluir: 'tarefas:excluir',
    deslocarSucessoras: 'tarefas:deslocar-sucessoras',
    ajustarDatasDaFase: 'tarefas:ajustar-datas-da-fase',
    criarFase: 'tarefas:criar-fase',
    atualizarFase: 'tarefas:atualizar-fase',
    excluirFase: 'tarefas:excluir-fase',
    reordenar: 'tarefas:reordenar',
    duplicar: 'tarefas:duplicar',
    copiarEstrutura: 'tarefas:copiar-estrutura',
    listarAgenda: 'tarefas:listar-agenda',
  },
  impressao: {
    exportarPdf: 'impressao:exportar-pdf',
    exportarAnalisePdf: 'impressao:exportar-analise-pdf',
  },
  ia: {
    estado: 'ia:estado',
    configurar: 'ia:configurar',
    removerChave: 'ia:remover-chave',
    analisar: 'ia:analisar',
    analisarPortfolio: 'ia:analisar-portfolio',
    conversar: 'ia:conversar',
    listarAnalises: 'ia:listar-analises',
    obterAnalise: 'ia:obter-analise',
    ultimaAnalise: 'ia:ultima-analise',
    excluirAnalise: 'ia:excluir-analise',
    obterInstrucoes: 'ia:obter-instrucoes',
    salvarInstrucoes: 'ia:salvar-instrucoes',
    restaurarChecklist: 'ia:restaurar-checklist',
    estadoAvs: 'ia:estado-avs',
    configurarAvs: 'ia:configurar-avs',
    removerChaveAvs: 'ia:remover-chave-avs',
    analisarAvs: 'ia:analisar-avs',
    ultimaAnaliseAvs: 'ia:ultima-analise-avs',
    conversarAvs: 'ia:conversar-avs',
    obterInstrucoesAvs: 'ia:obter-instrucoes-avs',
    salvarInstrucoesAvs: 'ia:salvar-instrucoes-avs',
    restaurarChecklistAvs: 'ia:restaurar-checklist-avs',
  },
  sds: {
    listar: 'sds:listar',
    obterPorAv: 'sds:obter-por-av',
  },
  avs: {
    listar: 'avs:listar',
    obter: 'avs:obter',
    criar: 'avs:criar',
    atualizarComercial: 'avs:atualizar-comercial',
    atualizarEquipe: 'avs:atualizar-equipe',
    listarMembros: 'avs:listar-membros',
    obterDashboard: 'avs:obter-dashboard',
    avancarEtapa: 'avs:avancar-etapa',
    declinar: 'avs:declinar',
    listarHistorico: 'avs:listar-historico',
    obterCatalogoCusto: 'avs:obter-catalogo-custo',
    obterSecaoCusto: 'avs:obter-secao-custo',
    salvarSecaoCusto: 'avs:salvar-secao-custo',
    obterSecaoProduto: 'avs:obter-secao-produto',
    salvarSecaoProduto: 'avs:salvar-secao-produto',
    obterSecaoProcesso: 'avs:obter-secao-processo',
    salvarSecaoProcesso: 'avs:salvar-secao-processo',
    abrirCaminho: 'avs:abrir-caminho',
    selecionarCaminho: 'avs:selecionar-caminho',
    listarAnexos: 'avs:listar-anexos',
    selecionarEAnexar: 'avs:selecionar-e-anexar',
    obterConteudoAnexo: 'avs:obter-conteudo-anexo',
    excluirAnexo: 'avs:excluir-anexo',
    gerarExemplos: 'avs:gerar-exemplos',
    listarTemplates: 'avs:listar-templates',
    salvarTemplate: 'avs:salvar-template',
    excluirTemplate: 'avs:excluir-template',
    finalizarECriarPreSd: 'avs:finalizar-criar-pre-sd',
    listarGrupos: 'avs:listar-grupos',
    criarGrupo: 'avs:criar-grupo',
    relatorio: 'avs:relatorio',
    obterSecaoPcp: 'avs:obter-secao-pcp',
    salvarSecaoPcp: 'avs:salvar-secao-pcp',
    obterContatos: 'avs:obter-contatos',
    salvarContatos: 'avs:salvar-contatos',
    aplicarAoGrupo: 'avs:aplicar-ao-grupo',
  },
  preferencias: {
    obter: 'preferencias:obter',
    definirTema: 'preferencias:definir-tema',
  },
  aparencia: {
    /** Canal síncrono (sendSync), lido pelo preload antes da primeira pintura. */
    obter: 'aparencia:obter',
  },
} as const;
