/** Nomes dos canais IPC. Usados em tempo de execução pelo main e pelo preload. */
export const CANAIS = {
  sessao: {
    obter: 'sessao:obter',
    entrar: 'sessao:entrar',
    sair: 'sessao:sair',
    primeiroAcesso: 'sessao:primeiro-acesso',
  },
  usuarios: {
    listar: 'usuarios:listar',
    criar: 'usuarios:criar',
    atualizar: 'usuarios:atualizar',
    alterarSenha: 'usuarios:alterar-senha',
    excluir: 'usuarios:excluir',
  },
  responsaveis: {
    listar: 'responsaveis:listar',
    criar: 'responsaveis:criar',
    atualizar: 'responsaveis:atualizar',
    excluir: 'responsaveis:excluir',
  },
  cronogramas: {
    listar: 'cronogramas:listar',
    obter: 'cronogramas:obter',
    criar: 'cronogramas:criar',
    atualizar: 'cronogramas:atualizar',
    excluir: 'cronogramas:excluir',
  },
  tarefas: {
    obterEstrutura: 'tarefas:obter-estrutura',
    criar: 'tarefas:criar',
    atualizar: 'tarefas:atualizar',
    excluir: 'tarefas:excluir',
    deslocarSucessoras: 'tarefas:deslocar-sucessoras',
    ajustarDatasDaFase: 'tarefas:ajustar-datas-da-fase',
    criarFase: 'tarefas:criar-fase',
    atualizarFase: 'tarefas:atualizar-fase',
    excluirFase: 'tarefas:excluir-fase',
    reordenar: 'tarefas:reordenar',
    duplicar: 'tarefas:duplicar',
    copiarEstrutura: 'tarefas:copiar-estrutura',
    listarAgenda: 'tarefas:listar-agenda',
  },
  impressao: {
    exportarPdf: 'impressao:exportar-pdf',
    exportarAnalisePdf: 'impressao:exportar-analise-pdf',
  },
  ia: {
    estado: 'ia:estado',
    configurar: 'ia:configurar',
    removerChave: 'ia:remover-chave',
    analisar: 'ia:analisar',
    analisarPortfolio: 'ia:analisar-portfolio',
    conversar: 'ia:conversar',
    listarAnalises: 'ia:listar-analises',
    obterAnalise: 'ia:obter-analise',
    ultimaAnalise: 'ia:ultima-analise',
    excluirAnalise: 'ia:excluir-analise',
    obterInstrucoes: 'ia:obter-instrucoes',
    salvarInstrucoes: 'ia:salvar-instrucoes',
    restaurarChecklist: 'ia:restaurar-checklist',
  },
  avs: {
    listar: 'avs:listar',
    obter: 'avs:obter',
    criar: 'avs:criar',
    atualizarComercial: 'avs:atualizar-comercial',
    atualizarEquipe: 'avs:atualizar-equipe',
    listarMembros: 'avs:listar-membros',
    obterDashboard: 'avs:obter-dashboard',
    avancarEtapa: 'avs:avancar-etapa',
    declinar: 'avs:declinar',
    listarHistorico: 'avs:listar-historico',
    obterCatalogoCusto: 'avs:obter-catalogo-custo',
    obterSecaoCusto: 'avs:obter-secao-custo',
    salvarSecaoCusto: 'avs:salvar-secao-custo',
    obterSecaoProduto: 'avs:obter-secao-produto',
    salvarSecaoProduto: 'avs:salvar-secao-produto',
    obterSecaoProcesso: 'avs:obter-secao-processo',
    salvarSecaoProcesso: 'avs:salvar-secao-processo',
    abrirCaminho: 'avs:abrir-caminho',
    listarAnexos: 'avs:listar-anexos',
    selecionarEAnexar: 'avs:selecionar-e-anexar',
    obterConteudoAnexo: 'avs:obter-conteudo-anexo',
    excluirAnexo: 'avs:excluir-anexo',
  },
  preferencias: {
    obter: 'preferencias:obter',
    definirTema: 'preferencias:definir-tema',
  },
  aparencia: {
    /** Canal síncrono (sendSync), lido pelo preload antes da primeira pintura. */
    obter: 'aparencia:obter',
  },
} as const;
